# Generated by Django 5.2.17 on 2026-08-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ticketcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_category_per_organization'),
        ),
    ]
